#!/bin/bash
# Runs the given command on the remote server.
#
# Examples:
#   $ nexec ls
#   $ nexec env
#   $ cat foo.sh | nexec bash
#   $ echo '{"foo":"bar"}' | nexec jq -r '.foo'

set -ueo pipefail

urlencode() {
  local length="${#1}"
  for (( i = 0; i < length; i++ )); do
    local c="${1:i:1}"
    case $c in
      [a-zA-Z0-9.~_-]) printf "$c" ;;
      *) printf '%%%02X' "'$c"
    esac
  done
}

cmd="$(urlencode "$1")"
shift

# https://stackoverflow.com/a/17841619/376773
join_by() { local IFS="$1"; shift; echo "$*"; }

args=("exit=1")
while [ $# -gt 0 ]; do
  args+=("arg=$(urlencode "$1")")
  shift
done

curl_args=("-sS" "--no-buffer" "--http1.0")
if [ ! -t 0 ]; then
  curl_args+=("--data-binary" "@-" "--header" "Transfer-Encoding: chunked")
fi

nexec_host="${NEXEC_HOST-https://nexec.n8.io}"
query="$(join_by '&' ${args[@]+"${args[@]}"})"
url="${nexec_host}/${cmd}?${query}"

# The `curl` command output goes to fd 3
exec 3< <(curl "${curl_args[@]}" ${NEXEC_CURL_ARGS-} "${url}")

# fd 4 sends everything except the very last line to stdout
exec 4> >(awk 'NR>1{print buf}{buf = $0}')

# The `tee` command dumps the curl output to fd 4,
# and only the last line goes to the `exit_code` variable
exit_code="$(tee <&3 /dev/fd/4 | tail -n 1)"
exit "${exit_code}"
